services:
  backrest:
    build: .
    container_name: backrest
    restart: unless-stopped
    environment:
      - BACKREST_CONFIG=/config/config.json
      - BACKREST_DATA=/data
      - TZ=Europe/Madrid
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    volumes:
      - ./config:/config
      - ./data:/data
      - ./cache:/cache
      - /opt:/opt:ro
      - /opt/backup:/backup
      - /etc/ssh:/etc/ssh:ro
      - /etc/fail2ban:/etc/fail2ban:ro
      - /etc/ufw:/etc/ufw:ro
      - /home/sophie/.ssh:/home/sophie/.ssh:ro
      - /home/blog-deploy/.ssh:/home/blog-deploy/.ssh:ro
      - /var/www:/var/www:ro
    networks:
      - proxy
      - database

networks:
  proxy:
    external: true
  database:
    external: true
