services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    volumes:
      - ./data:/app/data # Configuring persistent storage
    environment:
      - TZ=${TZ:-Europe/Madrid}
    networks:
      - proxy # add your own custom network config

networks:
  proxy:
    external: true
